[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; 自動下載您需要的函式庫
lib_deps =
    sstaub/Ethernet3 @ ^1.5.1
    olikraus/U8g2 @ ^2.35.9
    ricmoo/QRCode @ ^0.0.1
    h2zero/NimBLE-Arduino @ ^1.4.1

; 增加編譯速度與除錯等級
build_flags = 
    -D CORE_DEBUG_LEVEL=0