[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    sstaub/Ethernet3 @ ^1.5.1
    olikraus/U8g2 @ ^2.35.9
    ricmoo/QRCode @ ^0.0.1
    h2zero/NimBLE-Arduino @ ^1.4.1

; 強制排除標準 Ethernet 庫，避免衝突
lib_ignore = Ethernet